[package]
name = "cortex"
version = "0.1.0"
edition = "2018"
description = "Tensor operators & utilties."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.5.0"
ndarray = "0.15.3"
